language: python
install: pip install mkdocs
cache: pip

before_script:
  - git config user.name "Dominik Wisskirchen"
  - git config user.email "dominik.wisskirchen@ebf.de"
  - git remote add master "https://${GH_TOKEN}@github.com/ebf/jasonette-documentation.git";
  - git fetch master && git fetch master gh-pages:gh-pages;

script: mkdocs gh-deploy --clean --remote-name master